discount/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import re_path as url
from offer.views import recordSale, readme, addGasStaion, updateSucceed, confirmation, echo, updateView, searchView, addPromotion, getOverdraw_asManager, approveAudit, getOverdraw_asAuditor, dailyBalanceWork, approve, unaudited, paymentRequests, paymentDetail
from django.contrib.auth.views import LoginView, LogoutView
from accounts import views as accounts_view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [ 
    path('admin/', admin.site.urls),
    path('', searchView, name='search'),
    path('<int:pk>/<int:fuel_typ>/', updateView, name='update'),
    path('success/', echo, name='echo'),
    path('updateSucceed/', updateSucceed, name='updateSucceed'), 
    path('promotion/', addPromotion, name='promotion'),
    path('addgasstaion/', addGasStaion.as_view(), name='addGasStaion'),
    path('overdraw/', getOverdraw_asAuditor, name='overdraw'),
    path('recordSale/', recordSale, name='recordSale'),
    path('overfilled/<int:id>/', getOverdraw_asManager, name='overfilledAgent'),
    path('balance/<int:id>/', dailyBalanceWork, name='balance'),
    path('approve/<int:id>/', approve, name='approve'),
    path('audit/', unaudited, name='audit'),
    url('^audit/(?P<pk>[0-9]+)/(?P<start_date>\d{4}-\d{2}-\d{2})/(?P<end_date>\d{4}-\d{2}-\d{2})$', approveAudit, name = 'approveAudit'),
    path('payments/', paymentRequests, name='payments'),
    path('payments/<int:id>', paymentDetail, name='paymentDetail'),
    path('confirmation', confirmation, name='confirmation'),
    path('addmanager/', accounts_view.addManager, name='addManager'),
    path('addstaff/<str:act>/', accounts_view.addAuditorFinance, name='addAuditorFinance'),
    path('profile/', accounts_view.profile, name='profile'),
    path('profile/<int:id>/', accounts_view.profileEditor, name='profileEditor'),
    path('register/', accounts_view.register, name='register'),
    path('agents/', accounts_view.agentList, name='agents'),
    path('addagents/', accounts_view.addAgent, name='addagents'),
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('readme/', readme, name='readme')
]

if settings.DEBUG:
    urlpatterns  +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

offer/forms.py
from django import forms
from .models import Audited, Gas_offer, log_table

class SearchForm(forms.Form):
    search = forms.CharField()

class UpdateForm(forms.Form):
    filled_amount = forms.IntegerField()

class PromoCodeForm(forms.ModelForm):
    status= forms.BooleanField(widget=forms.CheckboxInput(attrs={'checked' : 'checked'}))
    class Meta:
        model = Gas_offer
        fields = ['plate_number','permited_amount', 'fuel', 'status']

class AuditForm(forms.ModelForm):
    start_date = forms.DateField()#widget=forms.TextInput())#attrs={ "id":"startDate"} ))
    end_date = forms.DateField()#widget=forms.DateInput(attrs={ "id":"endDate"} ))

    class Meta:
        model = log_table
        fields = ['gasstation']

class PaymentForm(forms.ModelForm):
    money_reciever = forms.CharField(widget=forms.Textarea(attrs={"rows":5 , "id":"money", "placeholder":"Full Informatin upto 250 character"}, ))
    class Meta:
        model=Audited
        fields = ['money_reciever']

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}

        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">  
  
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Luxurious+Roman&family=Noto+Serif+Ethiopic&display=swap" rel="stylesheet">
    
    <link rel="stylesheet" href="{% static 'css/jquery-ui.structure.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.theme.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}">
    
    <style>
      body {
        font-family: 'Noto Serif Ethiopic', serif;
      }
    </style>
  </head>
<body>   
    <div class="container mt-1 ">  
      <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid">
          <a class="navbar-brand py-0" href="{% url 'search' %}"><span style='font-size:35px;'>&#9981;</span></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              {% if user.is_staff %} 
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Action
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  
                  <li><a class="dropdown-item" href="{% url 'promotion' %}">Add Promo receiver</a></li>
                  <li><a class="dropdown-item" href="{% url 'addGasStaion' %}">Add gas staion</a></li>
                  <li><a class="dropdown-item" href="{% url 'addManager' %}">Add gas staion manager</a></li>
                  <li><a class="dropdown-item" href="{% url 'addAuditorFinance' act='auditor' %}">Add Auditor</a></li>
                  <li><a class="dropdown-item" href="{% url 'addAuditorFinance' act='finance' %}">Add Finance</a></li>
                  <li><a class="dropdown-item" href="#">Create report</a></li>
                  <li><a class="dropdown-item" href="{% url 'overdraw' %}">Over Fills</a></li>
                  
                  <li><a class="dropdown-item" href="{% url 'profile' %}">Profile</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">About</a></li>
                </ul>
                
              </li> 
              {% elif user.profile.role == 'manager' %}
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Action
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">                                               
                    <li><a class="dropdown-item" href="{% url 'agents' %}">Agents</a></li>                       
                    <li><a class="dropdown-item" href="{% url 'addagents' %}">Add Agents</a></li>                      
                    <li><a class="dropdown-item" href="{% url 'profile' %}">Profile</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="#">About</a></li>
                  </ul>                      
                </li>  
              {% elif user.profile.role == 'finance' %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Action
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">                                               
                  <li><a class="dropdown-item" href="{% url 'payments' %}">Finance</a></li>                              
                  <li><a class="dropdown-item" href="{% url 'profile' %}">Profile</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">About</a></li>
                </ul>                      
              </li>     
                    {% elif user.profile.role == 'auditor' %}
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <strong>Action</strong> 
                      </a>
                      <ul class="dropdown-menu" aria-labelledby="navbarDropdown">                                               
                        <li><a class="dropdown-item" href="{% url 'audit' %}">Audit</a></li>                              
                        <li><a class="dropdown-item" href="{% url 'profile' %}">Profile</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="#">About</a></li>
                      </ul>                      
                    </li>  
                  {% endif %} 
                    {% if user.is_authenticated %}
                      <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'profile' %}"><h5>{{user.username}}</h5></a>                            
                      </li>
                      <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'logout' %}"><h5>Logout</h5></a>                                   
                      </li>
                    {% else %}
                      <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'login' %}"><h5>Login</h5></a>                  
                      </li>
                    {% endif %}
                  
                	
               
            </ul>
            <!--
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
            -->
          </div>
        </div>
      </nav>
    </div>

    <div class="container mt-3 d-flex justify-content-center">
      
        {% block content %}
    
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <!--      
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.min.js" integrity="sha256-eTyxS0rkjpLEo16uXTS0uVCS4815lc40K2iVpWDvdSY=" crossorigin="anonymous"></script>
    -->
    <script src="{% static 'js/jqueryui/jquery.js' %}"></script>
    <script src="{% static 'js/jqueryui/jquery-ui.min.js' %}"></script>
    <script src="{% static 'js/jqueryui/main.js' %}"></script>
    <script>
      $(document).ready(function() {
  
      $("#id_start_date").datepicker({changeYear: true,changeMonth: true, dateFormat: 'yy-mm-dd'})
      $("#id_end_date").datepicker({changeYear: true,changeMonth: true, dateFormat: 'yy-mm-dd'})
      
             
       
      });
    </script>
  
</body>
</html>